sudo: false
language: python
cache: pip
matrix:
  include:
  - env: TOXENV=py35-lower_bound_deps
    python: 3.5
  - env: TOXENV=py36-lower_bound_deps
    python: 3.6
  - env: TOXENV=py37-lower_bound_deps
    python: 3.7
    sudo: required
    dist: xenial
  - env: TOXENV=py35-upper_bound_deps
    python: 3.5
  - env: TOXENV=py36-upper_bound_deps
    python: 3.6
  - env: TOXENV=py37-upper_bound_deps
    python: 3.7
    sudo: required
    dist: xenial
install:
- pip install tox coveralls
script:
- make test-ci
after_success:
- coveralls
notifications:
  email: false
  slack:
    secure: jbrRb54Epda/ra3j7B10zoOxl5sVxWQbyJtPVVuJ+mISDQJyt4FpJSl13ErtKrza5F++UAMs51qRwgicxTF7yN9mX/8RCDeCI+F4FmOWDTL7lPVCMlNyTAwE/UXL8XsAdoMN47gIkrYyUjnziwD//A+ZQ7pbTbMAzPBRyzH2tB5Ehp9eaU92T1oOGmh8j/rxBJuuQW3sfPb76IqR7F17vU5biDBN/FgWzTrWzS0J5VdbnvIfX+bMF+4VA/WRrCLg2GJyIuGeQtuKF4gBblsQVpu5ax8NnkM+ylWGrAgzzImJfhR+rt+VeZCImBvYiE8836mslqiu8lhQxQ96PbF8xdMy/qeKujPrHV6ilr5j3O2iVihd2vq48rAVwMoYtJL9+5I7g5G6lnlLLKhEahgTbT3GRc5r5bno8PhkqqQ3+YFyKbNeIqeH8SVF3sI740COK5MJ8/PHO9rc9kVhKrZ3n4Y6rPb7d92gW9XFcjKBukuJ7N0IeV+kSRvVZXJtN58bUkg4ZycEQ1jUUys4hMxh1opRn3IBBk4ZYyEMrswIdAjire3hE6Iq9aalSPDi0byg+skjT54VZgUMj/bFfUPzsLWr1PMXXmvCb4eskq9EoJVc43YrwaykMTx4phmqx+e2uBhd0LufFd8Kg2AfoyPMZplTpkV85uTvBy/5eCx1sG4=
